#!/usr/bin/env python3
"""Clone v551 → v551-2 and re-run schematic ingest (model A/B).

Prep copies pack inputs (PDF, uploads, boardview pin) without vision cache
or compiled schematic artefacts, registers v551-2 for the home/taxonomy UI,
and moves the sample repair off v551 so the library does not list duplicates.

Usage:
    # Prep only (copy + metadata) — run before switching models in .env
    .venv/bin/python scripts/run_v551_ingest.py --prepare-only

    # Prep + full schematic ingest on v551-2
    .venv/bin/python scripts/run_v551_ingest.py

    # Ingest only (skip copy) when v551-2 is already prepared
    .venv/bin/python scripts/run_v551_ingest.py --slug v551-2 --skip-prepare
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import shutil
import sys
import time
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

sys.stdout.reconfigure(line_buffering=True)  # noqa: SLF001

from anthropic import AsyncAnthropic

from api.config import get_settings
from api.logging_setup import configure_logging
from api.pipeline.schematic.orchestrator import ingest_schematic

logger = logging.getLogger("wrench_board.scripts.run_v551_ingest")

SOURCE_SLUG = "v551"
DEFAULT_SLUG = "v551-2"

# Re-generated by ingest_schematic — never copy from the source pack.
_SCHEMATIC_OUTPUT_FILES = (
    "electrical_graph.json",
    "schematic_graph.json",
    "parts_index.json",
    "nets_classified.json",
    "boot_sequence_analyzed.json",
    "passive_classification_llm.json",
    "simulator_reliability.json",
)

_REGISTRY_TEMPLATE = {
    "schema_version": "1.0",
    "device_label": "V551-2",
    "taxonomy": {
        "brand": "Tinno",
        "model": "V551",
        "version": "vision-retest",
        "form_factor": "phone_logic_board",
        "device_kind": "phone_logic_board",
    },
    "components": [],
}


def _default_pdf(slug: str, memory_root: Path) -> Path:
    pack_dir = memory_root / slug
    active = pack_dir / "schematic.pdf"
    if active.is_file():
        return active
    uploads = sorted(pack_dir.glob("uploads/*schematic*.pdf"))
    if uploads:
        return uploads[-1]
    raise SystemExit(f"No schematic PDF found under {pack_dir}")


def _purge_schematic_outputs(pack_dir: Path) -> None:
  pages = pack_dir / "schematic_pages"
  if pages.exists():
      shutil.rmtree(pages)
      logger.info("removed %s", pages)
  for name in _SCHEMATIC_OUTPUT_FILES:
      path = pack_dir / name
      if path.exists():
          path.unlink()
          logger.info("removed %s", path)


def _copy_pack_inputs(*, source: Path, target: Path) -> None:
    if not source.is_dir():
        raise SystemExit(f"Source pack missing: {source}")

    if target.exists():
        logger.info("refreshing target pack %s", target)
        _purge_schematic_outputs(target)
    else:
        target.mkdir(parents=True, exist_ok=True)

    for item in sorted(source.iterdir()):
        name = item.name
        if name == "schematic_pages" or name in _SCHEMATIC_OUTPUT_FILES:
            continue
        if name == "repairs":
            continue  # rewritten below with corrected slug
        dst = target / name
        if item.is_dir():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(item, dst)
        else:
            shutil.copy2(item, dst)
        logger.info("copied %s", name)

    _purge_schematic_outputs(target)


def _write_registry(pack_dir: Path, *, device_label: str) -> None:
    payload = json.loads(json.dumps(_REGISTRY_TEMPLATE))
    payload["device_label"] = device_label
    (pack_dir / "registry.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    )
    logger.info("wrote %s", pack_dir / "registry.json")


def _relocate_repairs(
    *,
    source: Path,
    target: Path,
    target_slug: str,
    device_label: str,
) -> None:
    src_repairs = source / "repairs"
    dst_repairs = target / "repairs"
    dst_repairs.mkdir(parents=True, exist_ok=True)

    moved = False
    for path in sorted(src_repairs.glob("*.json")):
        try:
            payload = json.loads(path.read_text())
        except json.JSONDecodeError:
            logger.warning("skip malformed repair %s", path)
            continue
        payload["device_slug"] = target_slug
        payload["device_label"] = device_label
        out = dst_repairs / path.name
        out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
        path.unlink()
        logger.info("moved repair %s → %s (%s)", path.name, target_slug, device_label)
        moved = True

    if not moved and not any(dst_repairs.glob("*.json")):
        repair_id = datetime.now(UTC).strftime("%Y%m%d%H%M%S")
        payload = {
            "repair_id": repair_id,
            "device_slug": target_slug,
            "device_label": device_label,
            "symptom": "V551 schematic vision re-test",
            "status": "open",
            "created_at": datetime.now(UTC).isoformat(),
        }
        (dst_repairs / f"{repair_id}.json").write_text(
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
        )
        logger.info("created fresh repair %s for %s", repair_id, target_slug)


def _reset_build_state(pack_dir: Path) -> None:
    payload = {
        "status": "running",
        "stage": "schematic",
        "error": None,
        "finished_at": None,
    }
    (pack_dir / "_build_state.json").write_text(json.dumps(payload, indent=2) + "\n")


def restore_v551(
    *,
    memory_root: Path,
    source_slug: str = SOURCE_SLUG,
    clone_slug: str = DEFAULT_SLUG,
    device_label: str = "V551",
) -> None:
    """Undo prepare_clone: repairs back on source_slug, drop stale failed build marker.

    The A/B clone moves repair metadata to v551-2 and leaves source without a
    ticket. This puts the canonical repair back on v551 and removes duplicate
    clone repairs from the home list. Schematic artefacts already on source are
    kept; only the Scout-failed _build_state marker is cleared so the UI does
    not show a permanent failed badge while the knowledge pack is still absent.
    """
    source = memory_root / source_slug
    clone = memory_root / clone_slug
    source_repairs = source / "repairs"
    source_repairs.mkdir(parents=True, exist_ok=True)

    # Repairs sitting under the clone → move back to source.
    clone_repairs = clone / "repairs"
    if clone_repairs.is_dir():
        for path in sorted(clone_repairs.glob("*.json")):
            try:
                payload = json.loads(path.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                logger.warning("skip malformed repair %s", path)
                continue
            payload["device_slug"] = source_slug
            payload["device_label"] = device_label
            out = source_repairs / path.name
            out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
            path.unlink()
            logger.info("restored repair %s → %s", path.name, source_slug)

    # Repairs left on source but still tagged with the clone slug (partial undo).
    for path in sorted(source_repairs.glob("*.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        if payload.get("device_slug") == clone_slug:
            payload["device_slug"] = source_slug
            payload["device_label"] = device_label
            path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
            logger.info("fixed repair slug on %s → %s", path.name, source_slug)

    # Drop Scout-failed marker; schematic ingest on source is already on disk.
    build_state = source / "_build_state.json"
    if build_state.is_file():
        try:
            state = json.loads(build_state.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            state = {}
        if state.get("status") == "failed":
            build_state.unlink()
            logger.info("removed stale failed _build_state on %s", source_slug)

    # Park the clone so it does not show build_state=running on unrelated repairs.
    if clone.is_dir():
        parked = {
            "status": "failed",
            "stage": "schematic",
            "error": "superseded — repairs restored to v551",
            "finished_at": datetime.now(UTC).isoformat(),
        }
        (clone / "_build_state.json").write_text(json.dumps(parked, indent=2) + "\n")
        logger.info("parked clone pack %s", clone_slug)


def prepare_clone(
    *,
    memory_root: Path,
    source_slug: str = SOURCE_SLUG,
    target_slug: str = DEFAULT_SLUG,
    device_label: str = "V551-2",
) -> Path:
    """Copy v551 inputs into v551-2, drop vision cache, fix UI metadata."""
    source = memory_root / source_slug
    target = memory_root / target_slug
    logger.info("prepare %s → %s", source_slug, target_slug)
    _copy_pack_inputs(source=source, target=target)
    _write_registry(target, device_label=device_label)
    _relocate_repairs(
        source=source,
        target=target,
        target_slug=target_slug,
        device_label=device_label,
    )
    _reset_build_state(target)
    logger.info("prepare complete — run ingest on %s when .env model is ready", target_slug)
    return target


async def _run(*, slug: str, pdf_path: Path) -> None:
    settings = get_settings()
    if not settings.anthropic_api_key:
        raise SystemExit("ANTHROPIC_API_KEY missing — copy .env.example to .env")

    pdf_path = pdf_path.resolve()
    if not pdf_path.is_file():
        raise SystemExit(f"PDF not found: {pdf_path}")

    client = AsyncAnthropic(
        api_key=settings.anthropic_api_key,
        max_retries=settings.anthropic_max_retries,
        base_url=settings.anthropic_base_url or None,
    )

    logger.info(
        "ingest start slug=%s pdf=%s model=%s base_url=%s concurrency=%d",
        slug,
        pdf_path,
        settings.anthropic_model_main,
        settings.anthropic_base_url or "(default)",
        settings.pipeline_vision_concurrency,
    )

    t0 = time.monotonic()
    graph = await ingest_schematic(
        device_slug=slug,
        pdf_path=pdf_path,
        client=client,
        memory_root=Path(settings.memory_root),
        model=settings.anthropic_model_main,
    )
    elapsed = time.monotonic() - t0
    logger.info(
        "ingest done in %.0fs components=%d nets=%d edges=%d rails=%d",
        elapsed,
        len(graph.components),
        len(graph.nets),
        len(graph.typed_edges),
        len(graph.power_rails),
    )


def main() -> None:
    configure_logging()
    settings = get_settings()
    memory_root = Path(settings.memory_root)

    parser = argparse.ArgumentParser(
        description="Clone v551 → v551-2 (no schematic_pages) and re-ingest for model comparison.",
    )
    parser.add_argument(
        "--source",
        default=SOURCE_SLUG,
        help=f"source pack slug (default: {SOURCE_SLUG})",
    )
    parser.add_argument(
        "--slug",
        default=DEFAULT_SLUG,
        help=f"target pack slug to ingest (default: {DEFAULT_SLUG})",
    )
    parser.add_argument(
        "--label",
        default="V551-2",
        help="device_label written to registry + repair metadata",
    )
    parser.add_argument(
        "--prepare-only",
        action="store_true",
        help="only copy/clean metadata; do not call ingest_schematic",
    )
    parser.add_argument(
        "--skip-prepare",
        action="store_true",
        help="skip clone step (target pack already prepared)",
    )
    parser.add_argument(
        "--pdf",
        type=Path,
        default=None,
        help="schematic PDF path (default: memory/{slug}/schematic.pdf or latest upload)",
    )
    parser.add_argument(
        "--restore",
        action="store_true",
        help="move repairs back from clone slug to source and clear stale failed build_state",
    )
    args = parser.parse_args()

    if args.restore:
        restore_v551(
            memory_root=memory_root,
            source_slug=args.source,
            clone_slug=args.slug,
            device_label="V551",
        )
        return

    if not args.skip_prepare:
        prepare_clone(
            memory_root=memory_root,
            source_slug=args.source,
            target_slug=args.slug,
            device_label=args.label,
        )

    if args.prepare_only:
        return

    pdf_path = args.pdf or _default_pdf(args.slug, memory_root)
    asyncio.run(_run(slug=args.slug, pdf_path=pdf_path))


if __name__ == "__main__":
    main()
