"""Regression tests for `scripts/dump_tools_inventory.py` and the
`api/agent/manifest.py` docstring family-count line.

Two layers of drift detection:

1. Markdown coverage — every tool name declared in MB_TOOLS, BV_TOOLS,
   PROFILE_TOOLS, PROTOCOL_TOOLS, CAM_TOOLS, CONSULT_TOOLS must appear
   verbatim in `docs/tools.md`. Adding a tool without re-running
   `make tools-inventory` flips this red.
2. Docstring counts — the leading docstring of `manifest.py` must
   mention each family's actual size (e.g. "MB_TOOLS: 14"). Adding a
   tool without bumping the docstring number flips this red.

Both checks run against the on-disk `docs/tools.md` regenerated by the
script, so the test also validates the script itself end-to-end.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

from api.agent import manifest

REPO = Path(__file__).resolve().parents[2]
DOCS_PATH = REPO / "docs" / "tools.md"
SCRIPT_PATH = REPO / "scripts" / "dump_tools_inventory.py"

GROUPS = (
    "MB_TOOLS",
    "BV_TOOLS",
    "PROFILE_TOOLS",
    "STOCK_TOOLS",
    "PROTOCOL_TOOLS",
    "CAM_TOOLS",
    "CONSULT_TOOLS",
)


def _run_script() -> None:
    """Invoke the dump script using the same Python interpreter."""
    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH)],
        cwd=str(REPO),
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, (
        f"dump_tools_inventory.py exited {result.returncode}\n"
        f"stdout={result.stdout}\nstderr={result.stderr}"
    )


def test_dump_script_runs_and_writes_docs_tools_md() -> None:
    _run_script()
    assert DOCS_PATH.exists(), "docs/tools.md missing after script run"
    body = DOCS_PATH.read_text(encoding="utf-8")
    assert body.startswith(
        "# Tools manifest (auto-généré, ne pas éditer à la main)"
    )
    assert "make tools-inventory" in body


def test_dump_script_is_idempotent() -> None:
    """Two consecutive runs must leave docs/tools.md byte-identical."""
    _run_script()
    first = DOCS_PATH.read_bytes()
    _run_script()
    second = DOCS_PATH.read_bytes()
    assert first == second, (
        "dump_tools_inventory.py is not idempotent — second run changed "
        "the file. Inspect the diff and remove non-deterministic content "
        "(timestamps, dict-iteration order, …)."
    )


@pytest.mark.parametrize("group_attr", GROUPS)
def test_every_tool_name_appears_in_markdown(group_attr: str) -> None:
    _run_script()
    body = DOCS_PATH.read_text(encoding="utf-8")
    for tool in getattr(manifest, group_attr):
        name = tool["name"]
        # 脚本将每个工具renders为`### \`name\`标题；我们
        # 匹配反引号包裹的形式以避免 accidental hits
        # 散文图。
        needle = f"`{name}`"
        assert needle in body, (
            f"tool {name} from {group_attr} missing from docs/tools.md — "
            f"run `make tools-inventory` to regenerate."
        )


def test_summary_table_counts_match_module() -> None:
    """The Sommaire table at the top must list the actual group sizes."""
    _run_script()
    body = DOCS_PATH.read_text(encoding="utf-8")
    # 每个系列标题还嵌入计数：“## <标签> — N 工具”。
    expected_counts = {
        "MB_TOOLS": len(manifest.MB_TOOLS),
        "BV_TOOLS": len(manifest.BV_TOOLS),
        "PROFILE_TOOLS": len(manifest.PROFILE_TOOLS),
        "STOCK_TOOLS": len(manifest.STOCK_TOOLS),
        "PROTOCOL_TOOLS": len(manifest.PROTOCOL_TOOLS),
        "CAM_TOOLS": len(manifest.CAM_TOOLS),
        "CONSULT_TOOLS": len(manifest.CONSULT_TOOLS),
    }
    # 通过每个家庭的标题行进行抽查。
    headings = re.findall(r"^## .+ — (\d+) tool\(s\)$", body, flags=re.M)
    actual_counts = [int(c) for c in headings]
    assert actual_counts == [
        expected_counts["MB_TOOLS"],
        expected_counts["BV_TOOLS"],
        expected_counts["PROFILE_TOOLS"],
        expected_counts["STOCK_TOOLS"],
        expected_counts["PROTOCOL_TOOLS"],
        expected_counts["CAM_TOOLS"],
        expected_counts["CONSULT_TOOLS"],
    ], f"family counts in docs/tools.md drifted: {actual_counts}"


def test_manifest_docstring_mentions_actual_family_counts() -> None:
    """The leading docstring of manifest.py must state the real count
    per family. Catches the drift that motivated this whole patch
    (the original docstring said "4 tools" while MB_TOOLS held 14)."""
    doc = manifest.__doc__ or ""
    cases = {
        "MB_TOOLS": len(manifest.MB_TOOLS),
        "BV_TOOLS": len(manifest.BV_TOOLS),
        "PROFILE_TOOLS": len(manifest.PROFILE_TOOLS),
        "STOCK_TOOLS": len(manifest.STOCK_TOOLS),
        "PROTOCOL_TOOLS": len(manifest.PROTOCOL_TOOLS),
        "CAM_TOOLS": len(manifest.CAM_TOOLS),
        "CONSULT_TOOLS": len(manifest.CONSULT_TOOLS),
    }
    for group_name, expected in cases.items():
        # 我们require文档字符串来mention姓氏及其
        # 同一逻辑行中某处re的精确计数（仅分隔
        # 按标点符号/whitespace）。
        pattern = re.compile(
            rf"{re.escape(group_name)}\s*:\s*{expected}\b",
            flags=re.IGNORECASE,
        )
        assert pattern.search(doc), (
            f"manifest.py docstring is out of date for {group_name}: "
            f"expected '{group_name}: {expected}', got docstring head:\n"
            f"{doc[:400]}"
        )
